name: Terraform init and validate

on: [push, pull_request]

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  tf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2

    - name: build application
      run: make install 

    - name: Terraform fmt
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color
